add dispatcher
mrMakaronka/pyenv pull request #8
Opened 2020-11-05 11:03 UTC by AlvinMax

2020-11-05 11:15 UTC, faucct commented on src/main/python/ipystate/impl/dispatcher.py
> +        # noinspection PyUnresolvedReferences
Это фиксится type-хинтом.

2020-11-09 07:02 UTC, faucct requested changes

2020-11-09 07:02 UTC, faucct commented on setup.py
> +        'pyarrow==0.17.1'
Лучше ставить trailing comma, чтобы не создавать шум в VCS при последующих добавлениях.

2020-11-09 07:02 UTC, faucct commented on src/main/python/ipystate/impl/dispatch/common.py
>  def _function_constructor(code, fglobals, name, argdefs, closure, kwdefaults, fdict, annotations, qualname,
Лучше в подобных случаях делать перенос перед аргументами: так не будет ехать индентация при переименованиях:

```
def _function_constructor(
    code,
):
```

2020-11-09 07:02 UTC, faucct commented on src/main/python/ipystate/impl/dispatch/common.py
> +            return ref(UserDict(), *args)
Я совсем не понимаю, что тут происходит: почему мёртвая ссылка подменяется на `UserDict()`? Может быть какими-нибудь тестами покрыть?

2020-11-09 07:02 UTC, faucct commented on src/main/python/ipystate/impl/dispatch/dataframe.py
> +    def _all_str(cols) -> bool:
https://docs.python.org/3/library/functions.html#all

2020-11-09 07:02 UTC, faucct commented on src/main/python/ipystate/impl/dispatch/tensorflow.py
> +                    file.write(pybase64.b64decode(value))
К моему сожалению, `pybase64` – это не встроенный пакет и его надо добавлять в `setup.py`.

2020-11-09 10:06 UTC, faucct commented on setup.py
> +        'pyarrow==0.17.1',
Давай не лочить тут так жёстко версию. Можешь попробовать подобрать первую и последнюю версию, с которыми работает.

2020-11-09 10:11 UTC, AlvinMax commented on setup.py
> +        'pyarrow==0.17.1',
Ну мы же сейчас и так ее фиксируем через requirements?

2020-11-09 10:13 UTC, faucct commented on setup.py
> +        'pyarrow==0.17.1',
В идеале не должны и я хочу оставить там по минимуму ограничений.

2020-11-09 12:31 UTC, merged